spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/tistory
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  session:
    store-type: redis
    timeout: 30m